
services:

  mqtt:
    build:
      context: ./
      dockerfile: ./mqtt.Dockerfile
    image: openmoxie/openmoxie-mqtt:${OPENMOXIE_VERSION:-latest}
    ports:
      - "8883:8883"
    volumes:
      - ./local/work:/mosquitto/log

  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: openmoxie/openmoxie-server:${OPENMOXIE_VERSION:-latest}
    expose:
      - "8000"
    volumes:
      - ./local/work:/app/site/work
    depends_on:
      - mqtt